### ISSUE TITLE
Double commande execute give player free packtages

### ISSUE THREAD

**Issue by estebanlll** [BuycraftPlugin/Tebex-Gmod#9]
Some time commande get executed twice 

I think some check can run on same time or idk but some time online commanded get duplicated 
![photo_2024-03-07_18-15-40](https://github.com/tebexio/Tebex-Gmod/assets/19195363/0a283643-6709-4479-8e21-d097d96e9f39)
![photo_2024-03-07_16-27-46](https://github.com/tebexio/Tebex-Gmod/assets/19195363/2f640acb-e4ad-449d-9d2e-5313aa0840fb)

Player buy one the package but command get doubled

**Comment by WildBamaBoy** [comment]
Hi there, please confirm that you only have Tebex installed and running once. Also check in your store panel, are there multiple commands being executed there or are you only seeing the duplicates in the plugin?

**Comment by WildBamaBoy** [comment]
We are unable to reproduce this issue, please ensure Tebex is only installed once and that the command is also not duplicated in your store panel.
